name: CI for DhcpRouteConverter
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        graalvm: '21'
        java: '21'
        native-image: true
    - name: Run tests
      run: mvn clean test
    - name: Build
      run: mvn clean package

