name: CI for DhcpRouteConverter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GraalVM JDK 21
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image: true

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Install netconf-java dependency
      run: |
        mvn install:install-file \
          -Dfile=lib/netconf-java-2.1.1.7.jar \
          -DpomFile=lib/netconf-java-2.1.1.7.pom \
          -DgroupId=net.juniper.netconf \
          -DartifactId=netconf-java \
          -Dversion=2.1.1.7 \
          -Dpackaging=jar

    - name: Run tests and build
      run: mvn clean package

    - name: Test binary with QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user
        qemu-x86_64 -cpu qemu64 ./target/DhcpRouteConverter -tdo 192.168.0.0/16,127.0.0.192

    - name: Upload .deb artifact
      uses: actions/upload-artifact@v4
      with:
        name: DhcpRouteConverter-deb
        path: target/DhcpRouteConverter_*.deb
        if-no-files-found: error