name: CI for DhcpRouteConverter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up GraalVM JDK 21
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image: true

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Clone and build netconf-java
      run: |
        # Клонуємо netconf-java
        git clone https://github.com/Juniper/netconf-java.git
        cd netconf-java
        # Модифікуємо pom.xml
        sed -i "s,com.jcraft,com.github.mwiede," pom.xml
        sed -i "s,0\.1\.55,2.27.0," pom.xml
        # Збираємо netconf-java
        mvn clean package -DskipTests
        # Визначаємо версію
        VERSION=$(find ./target -name '*.jar' | head -1 | sed "s,^[^0-9]*,,;s,-.*\.jar$,,")
        cp pom.xml ./target/netconf-java-${VERSION}.pom
        # Встановлюємо артефакт у локальний Maven-репозиторій
        mvn install:install-file \
          -Dfile=target/netconf-java-${VERSION}.jar \
          -DpomFile=target/netconf-java-${VERSION}.pom \
          -DgroupId=net.juniper.netconf \
          -DartifactId=netconf-java \
          -Dversion=${VERSION} \
          -Dpackaging=jar

    - name: Run tests and build
      run: mvn clean package

    - name: Test binary with QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user
        qemu-x86_64 -cpu qemu64 ./target/DhcpRouteConverter -tdo 192.168.0.0/16,127.0.0.192

    - name: Upload .deb artifact
      uses: actions/upload-artifact@v4
      with:
        name: DhcpRouteConverter-deb
        path: target/DhcpRouteConverter_*.deb
        if-no-files-found: error