name: CI for DhcpRouteConverter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    # Виконується на ubuntu-latest (найновіша версія Ubuntu).
    runs-on: ubuntu-latest

    steps:
    # Checkout repository: Клонує репозиторій.
    - name: Checkout repository
      uses: actions/checkout@v4

    # Set up GraalVM JDK 21: Встановлює GraalVM JDK 21 із native-image.
    - name: Set up GraalVM JDK 21
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}
        native-image: true

    # Cache Maven dependencies: Кешує залежності Maven для прискорення збірки.
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    # Run tests and build: Запускає mvn clean package, що виконує тести 
    # (через maven-surefire-plugin) і створює бінарник та .deb.
    - name: Run tests and build
      run: mvn clean package

    # Upload .deb artifact: Завантажує target/DhcpRouteConverter_1.0.0_all.deb
    # як артефакт, доступний у вкладці Actions на GitHub.
    - name: Upload .deb artifact
      uses: actions/upload-artifact@v4
      with:
        name: DhcpRouteConverter-deb
        path: target/DhcpRouteConverter_1.0.0_all.deb
        if-no-files-found: error
